# This is a basic workflow to help you get started with Actions

name: Discord Release Message

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
      
      - name: Send Release Message
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:          
          endpoint: https://codey-bot.herokuapp.com/api/send
          configuration: '{ "method": "POST", "body": "{\"channelId\":\"933990639178252308\",\"message\":\"nice\",\"secret\":\"abc\"}" }'
